package ai.houyi.openssp.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.description
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.keywords
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.media_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer mediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.media_app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String mediaAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.pkg_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String pkgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.download_url
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String downloadUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.paid
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.category
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.os
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.ext
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String ext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.name
     *
     * @return the value of app.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.name
     *
     * @param name the value for app.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.description
     *
     * @return the value of app.description
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.description
     *
     * @param description the value for app.description
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.keywords
     *
     * @return the value of app.keywords
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.keywords
     *
     * @param keywords the value for app.keywords
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.media_id
     *
     * @return the value of app.media_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.media_id
     *
     * @param mediaId the value for app.media_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_id
     *
     * @return the value of app.app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_id
     *
     * @param appId the value for app.app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.media_app_id
     *
     * @return the value of app.media_app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getMediaAppId() {
        return mediaAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.media_app_id
     *
     * @param mediaAppId the value for app.media_app_id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setMediaAppId(String mediaAppId) {
        this.mediaAppId = mediaAppId == null ? null : mediaAppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.pkg_name
     *
     * @return the value of app.pkg_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getPkgName() {
        return pkgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.pkg_name
     *
     * @param pkgName the value for app.pkg_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setPkgName(String pkgName) {
        this.pkgName = pkgName == null ? null : pkgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.download_url
     *
     * @return the value of app.download_url
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.download_url
     *
     * @param downloadUrl the value for app.download_url
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.paid
     *
     * @return the value of app.paid
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.paid
     *
     * @param paid the value for app.paid
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setPaid(Integer paid) {
        this.paid = paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.category
     *
     * @return the value of app.category
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.category
     *
     * @param category the value for app.category
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.os
     *
     * @return the value of app.os
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.os
     *
     * @param os the value for app.os
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setOs(Integer os) {
        this.os = os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.create_time
     *
     * @return the value of app.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.create_time
     *
     * @param createTime the value for app.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.update_time
     *
     * @return the value of app.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.update_time
     *
     * @param updateTime the value for app.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.status
     *
     * @return the value of app.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.status
     *
     * @param status the value for app.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.ext
     *
     * @return the value of app.ext
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.ext
     *
     * @param ext the value for app.ext
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static App.Builder builder() {
        return new App.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private App obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new App();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.id
         *
         * @param id the value for app.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.name
         *
         * @param name the value for app.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.description
         *
         * @param description the value for app.description
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder description(String description) {
            obj.setDescription(description);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.keywords
         *
         * @param keywords the value for app.keywords
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder keywords(String keywords) {
            obj.setKeywords(keywords);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.media_id
         *
         * @param mediaId the value for app.media_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mediaId(Integer mediaId) {
            obj.setMediaId(mediaId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.app_id
         *
         * @param appId the value for app.app_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder appId(String appId) {
            obj.setAppId(appId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.media_app_id
         *
         * @param mediaAppId the value for app.media_app_id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder mediaAppId(String mediaAppId) {
            obj.setMediaAppId(mediaAppId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.pkg_name
         *
         * @param pkgName the value for app.pkg_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder pkgName(String pkgName) {
            obj.setPkgName(pkgName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.download_url
         *
         * @param downloadUrl the value for app.download_url
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder downloadUrl(String downloadUrl) {
            obj.setDownloadUrl(downloadUrl);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.paid
         *
         * @param paid the value for app.paid
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder paid(Integer paid) {
            obj.setPaid(paid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.category
         *
         * @param category the value for app.category
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder category(Integer category) {
            obj.setCategory(category);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.os
         *
         * @param os the value for app.os
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder os(Integer os) {
            obj.setOs(os);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.create_time
         *
         * @param createTime the value for app.create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.update_time
         *
         * @param updateTime the value for app.update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.status
         *
         * @param status the value for app.status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column app.ext
         *
         * @param ext the value for app.ext
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder ext(String ext) {
            obj.setExt(ext);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public App build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table app
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", false),
        description("description", "description", "VARCHAR", false),
        keywords("keywords", "keywords", "VARCHAR", false),
        mediaId("media_id", "mediaId", "INTEGER", false),
        appId("app_id", "appId", "VARCHAR", false),
        mediaAppId("media_app_id", "mediaAppId", "VARCHAR", false),
        pkgName("pkg_name", "pkgName", "VARCHAR", false),
        downloadUrl("download_url", "downloadUrl", "VARCHAR", false),
        paid("paid", "paid", "INTEGER", false),
        category("category", "category", "INTEGER", false),
        os("os", "os", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        status("status", "status", "INTEGER", false),
        ext("ext", "ext", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}