package ai.houyi.openssp.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.login_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.password
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.contact
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.email
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.qq
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.telephone
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.bank_account
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.bank_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.account_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.currency
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.audit_status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Integer auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publisher.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.id
     *
     * @return the value of publisher.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.id
     *
     * @param id the value for publisher.id
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.name
     *
     * @return the value of publisher.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.name
     *
     * @param name the value for publisher.name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.login_name
     *
     * @return the value of publisher.login_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.login_name
     *
     * @param loginName the value for publisher.login_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.password
     *
     * @return the value of publisher.password
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.password
     *
     * @param password the value for publisher.password
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.contact
     *
     * @return the value of publisher.contact
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.contact
     *
     * @param contact the value for publisher.contact
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.email
     *
     * @return the value of publisher.email
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.email
     *
     * @param email the value for publisher.email
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.qq
     *
     * @return the value of publisher.qq
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.qq
     *
     * @param qq the value for publisher.qq
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.telephone
     *
     * @return the value of publisher.telephone
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.telephone
     *
     * @param telephone the value for publisher.telephone
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.bank_account
     *
     * @return the value of publisher.bank_account
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.bank_account
     *
     * @param bankAccount the value for publisher.bank_account
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.bank_name
     *
     * @return the value of publisher.bank_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.bank_name
     *
     * @param bankName the value for publisher.bank_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.account_name
     *
     * @return the value of publisher.account_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.account_name
     *
     * @param accountName the value for publisher.account_name
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.currency
     *
     * @return the value of publisher.currency
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.currency
     *
     * @param currency the value for publisher.currency
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setCurrency(Integer currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.status
     *
     * @return the value of publisher.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.status
     *
     * @param status the value for publisher.status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.audit_status
     *
     * @return the value of publisher.audit_status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.audit_status
     *
     * @param auditStatus the value for publisher.audit_status
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.create_time
     *
     * @return the value of publisher.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.create_time
     *
     * @param createTime the value for publisher.create_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publisher.update_time
     *
     * @return the value of publisher.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publisher.update_time
     *
     * @param updateTime the value for publisher.update_time
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publisher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Publisher.Builder builder() {
        return new Publisher.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table publisher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Publisher obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Publisher();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.id
         *
         * @param id the value for publisher.id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.name
         *
         * @param name the value for publisher.name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.login_name
         *
         * @param loginName the value for publisher.login_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder loginName(String loginName) {
            obj.setLoginName(loginName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.password
         *
         * @param password the value for publisher.password
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder password(String password) {
            obj.setPassword(password);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.contact
         *
         * @param contact the value for publisher.contact
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder contact(String contact) {
            obj.setContact(contact);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.email
         *
         * @param email the value for publisher.email
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder email(String email) {
            obj.setEmail(email);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.qq
         *
         * @param qq the value for publisher.qq
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qq(String qq) {
            obj.setQq(qq);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.telephone
         *
         * @param telephone the value for publisher.telephone
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder telephone(String telephone) {
            obj.setTelephone(telephone);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.bank_account
         *
         * @param bankAccount the value for publisher.bank_account
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bankAccount(String bankAccount) {
            obj.setBankAccount(bankAccount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.bank_name
         *
         * @param bankName the value for publisher.bank_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder bankName(String bankName) {
            obj.setBankName(bankName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.account_name
         *
         * @param accountName the value for publisher.account_name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder accountName(String accountName) {
            obj.setAccountName(accountName);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.currency
         *
         * @param currency the value for publisher.currency
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder currency(Integer currency) {
            obj.setCurrency(currency);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.status
         *
         * @param status the value for publisher.status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder status(Integer status) {
            obj.setStatus(status);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.audit_status
         *
         * @param auditStatus the value for publisher.audit_status
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder auditStatus(Integer auditStatus) {
            obj.setAuditStatus(auditStatus);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.create_time
         *
         * @param createTime the value for publisher.create_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column publisher.update_time
         *
         * @param updateTime the value for publisher.update_time
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Publisher build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table publisher
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", false),
        loginName("login_name", "loginName", "VARCHAR", false),
        password("password", "password", "VARCHAR", false),
        contact("contact", "contact", "VARCHAR", false),
        email("email", "email", "VARCHAR", false),
        qq("qq", "qq", "VARCHAR", false),
        telephone("telephone", "telephone", "VARCHAR", false),
        bankAccount("bank_account", "bankAccount", "VARCHAR", false),
        bankName("bank_name", "bankName", "VARCHAR", false),
        accountName("account_name", "accountName", "VARCHAR", false),
        currency("currency", "currency", "INTEGER", false),
        status("status", "status", "INTEGER", false),
        auditStatus("audit_status", "auditStatus", "INTEGER", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table publisher
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}