package ai.houyi.openssp.mapper;

import ai.houyi.openssp.model.MediaFloorTrafficAttr;
import ai.houyi.openssp.model.example.MediaFloorTrafficAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MediaFloorTrafficAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    long countByExample(MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int deleteByExample(MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int insert(MediaFloorTrafficAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int insertSelective(MediaFloorTrafficAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    MediaFloorTrafficAttr selectOneByExample(MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    List<MediaFloorTrafficAttr> selectByExample(MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    MediaFloorTrafficAttr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") MediaFloorTrafficAttr record, @Param("example") MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByExample(@Param("record") MediaFloorTrafficAttr record, @Param("example") MediaFloorTrafficAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByPrimaryKeySelective(MediaFloorTrafficAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByPrimaryKey(MediaFloorTrafficAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<MediaFloorTrafficAttr> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_floor_traffic_attr
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<MediaFloorTrafficAttr> list, @Param("selective") MediaFloorTrafficAttr.Column ... selective);
}