package ai.houyi.openssp.mapper;

import ai.houyi.openssp.model.SiteAdPosition;
import ai.houyi.openssp.model.example.SiteAdPositionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteAdPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    long countByExample(SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int deleteByExample(SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int insert(SiteAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int insertSelective(SiteAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SiteAdPosition selectOneByExample(SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    List<SiteAdPosition> selectByExample(SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    SiteAdPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") SiteAdPosition record, @Param("example") SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByExample(@Param("record") SiteAdPosition record, @Param("example") SiteAdPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByPrimaryKeySelective(SiteAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated Tue Dec 04 19:59:17 CST 2018
     */
    int updateByPrimaryKey(SiteAdPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SiteAdPosition> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_ad_position
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SiteAdPosition> list, @Param("selective") SiteAdPosition.Column ... selective);
}